alias: Dining Room Motion Lights
description: ""
triggers:
  - entity_id: binary_sensor.dining_room_hue_motion_sensor
    to: "on"
    trigger: state
  - entity_id: binary_sensor.dining_room_hue_motion_sensor
    to: "off"
    for: "00:10:00"
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.dining_room_hue_motion_sensor
            state: "on"
          - condition: numeric_state
            entity_id: sensor.dining_room_hue_motion_sensor_illuminance
            below: 18
        sequence:
          - target:
              entity_id: light.dining_room_lights
            data:
              color_temp_kelvin: 2700
              brightness: 255
              transition: 4
            action: light.turn_on
      - conditions:
          - condition: state
            entity_id: binary_sensor.dining_room_hue_motion_sensor
            state: "off"
        sequence:
          - target:
              entity_id: light.dining_room_lights
            data:
              transition: 4
            action: light.turn_off
mode: restart
