alias: Pantry motion lights
description: ""
triggers:
  - entity_id: binary_sensor.ikea_motion_1_occupancy
    to: "on"
    trigger: state
  - entity_id: binary_sensor.ikea_motion_1_occupancy
    to: "off"
    for: "00:00:30"
    trigger: state
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.ikea_motion_1_occupancy
            state: "on"
        sequence:
          - target:
              entity_id: light.pantry_lights
            action: light.turn_on
            data:
              brightness: 38
      - conditions:
          - condition: state
            entity_id: binary_sensor.ikea_motion_1_occupancy
            state: "off"
        sequence:
          - target:
              entity_id: light.pantry_lights
            action: light.turn_off
            data: {}
mode: restart
