alias: Living Room Motion Lights
triggers:
  - entity_id: binary_sensor.hue_motion_sensor
    to: "on"
    trigger: state
  - entity_id: binary_sensor.hue_motion_sensor
    to: "off"
    for: "00:10:00"
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.hue_motion_sensor
            state: "on"
          - condition: numeric_state
            entity_id: sensor.hue_motion_sensor_illuminance
            below: 10
          - condition: state
            entity_id: input_boolean.night_light_mode
            state: "off"
        sequence:
          - if:
              - condition: state
                entity_id: input_boolean.motion_lights_master_switch
                state: "on"
            then:
              - target:
                  entity_id: switch.living_room_lights
                action: switch.turn_on
                data: {}
          - target:
              entity_id: light.living_room_lights
            action: light.turn_on
            data:
              color_temp_kelvin: 2700
              brightness_pct: 100
      - conditions:
          - condition: state
            entity_id: binary_sensor.hue_motion_sensor
            state: "on"
          - condition: numeric_state
            entity_id: sensor.hue_motion_sensor_illuminance
            below: 10
        sequence:
          - target:
              entity_id: light.living_room_lights
            action: light.turn_on
            data:
              rgb_color: >
                {{ states('input_text.night_light_color_hue').split(',') |
                map('int') | list }}
              brightness_pct: 41
              transition: 4
      - conditions:
          - condition: state
            entity_id: binary_sensor.hue_motion_sensor
            state: "off"
        sequence:
          - target:
              entity_id: switch.living_room_lights
            action: switch.turn_off
            data: {}
          - target:
              entity_id: light.living_room_lights
            action: light.turn_off
            data: {}
mode: restart
