alias: Living Room Motion Lights
triggers:
  - entity_id: binary_sensor.hue_motion_sensor
    to: "on"
    trigger: state
  - entity_id: binary_sensor.hue_motion_sensor
    to: "off"
    for: "00:10:00"
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.hue_motion_sensor
            state: "on"
          - condition: numeric_state
            entity_id: sensor.hue_motion_sensor_illuminance
            below: 10
        sequence:
          - target:
              entity_id: switch.living_room_lights
            action: switch.turn_on
            data: {}
      - conditions:
          - condition: state
            entity_id: binary_sensor.hue_motion_sensor
            state: "off"
        sequence:
          - target:
              entity_id: switch.living_room_lights
            action: switch.turn_off
            data: {}
mode: restart
