alias: HVAC for time-of-use rates
description: >-
  HVAC shallow, long cool starting at 1am in summer to take advantage of
  time-of-use rates.
triggers:
  - at:
      - "22:05:00"
      - "23:05:00"
      - "04:05:00"
      - "17:40:00"
      - "17:55:00"
      - "21:05:00"
    trigger: time
conditions:
  - condition: template
    value_template: "{{ now().month in [5, 6, 7, 8, 9] }}"
actions:
  - variables:
      time_action_map:
        "22:05": decrease_1
        "23:05": decrease_1
        "04:05": decrease_1
        "17:40": decrease_1
        "17:55": "off"
        "21:05": "on"
      current_time: "{{ now().strftime('%H:%M') }}"
  - data:
      action: "{{ time_action_map[current_time] }}"
    action: python_script.hvac_pre_cool_and_time_of_use
mode: single
