alias: HVAC Pre-cool and TOU Actions
description: Run HVAC pre-cool script with different actions on specific summer times
triggers:
  - at:
      - "14:00:00"
      - "15:00:00"
      - "16:00:00"
      - "17:55:00"
      - "21:05:00"
    trigger: time
conditions:
  - condition: template
    value_template: "{{ now().month in [4, 5, 6, 7, 8, 9] }}"
actions:
  - variables:
      time_action_map:
        "14:00": decrease_1
        "15:00": decrease_1
        "16:00": decrease_1
        "17:55": "off"
        "21:05": "on"
      current_time: "{{ now().strftime('%H:%M') }}"
  - data:
      action: "{{ time_action_map[current_time] }}"
    action: python_script.hvac_pre_cool_and_time_of_use
mode: single
