alias: Master Bedroom Motion Light
description: ""
triggers:
  - entity_id: binary_sensor.hue_motion_4
    to: "on"
    trigger: state
  - entity_id: binary_sensor.hue_motion_4
    to: "off"
    for: "00:01:00"
    trigger: state
conditions:
  - condition: state
    entity_id: input_boolean.motion_lights_master_switch
    state: "on"
  - condition: sun
    after: sunset
    after_offset: "-01:00:00"
    before: sunrise
    before_offset: "00:30:00"
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.hue_motion_4
            state: "on"
          - condition: time
            after: "20:00:00"
            before: "06:00:00"
        sequence:
          - target:
              entity_id: light.ufo_lamp
            data:
              rgb_color:
                - 255
                - 0
                - 0
              brightness: 1
            action: light.turn_on
          - target:
              entity_id: light.ufo_lamp
            data:
              rgb_color:
                - 255
                - 0
                - 0
              brightness: 255
            action: light.turn_on
          - action: switch.turn_off
            target:
              entity_id:
                - switch.tr_plug_1
                - switch.tr_plug_3
                - switch.shelly_plug_1
      - conditions:
          - condition: state
            entity_id: binary_sensor.hue_motion_4
            state: "on"
          - condition: time
            after: "15:00:00"
            before: "20:00:00"
        sequence:
          - target:
              entity_id: light.ufo_lamp
            data:
              color_temp_kelvin: 2000
              brightness: 1
            action: light.turn_on
          - target:
              entity_id: light.ufo_lamp
            data:
              color_temp_kelvin: 2000
              brightness: 255
            action: light.turn_on
          - action: switch.turn_on
            target:
              entity_id:
                - switch.tr_plug_1
                - switch.tr_plug_3
                - switch.shelly_plug_1
      - conditions:
          - condition: state
            entity_id: binary_sensor.hue_motion_4
            state: "off"
        sequence:
          - target:
              entity_id: light.ufo_lamp
            data: {}
            action: light.turn_off
          - action: switch.turn_off
            target:
              entity_id:
                - switch.tr_plug_1
                - switch.tr_plug_3
                - switch.shelly_plug_1
mode: restart
