alias: Update Calendar
description: ""
triggers:
  - trigger: time_pattern
    minutes: /15
conditions: []
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - calendar.family
mode: single
