alias: Auto turn off switches after delay
mode: restart
trigger:
  - platform: state
    entity_id:
      - switch.tr_plug_4
      - switch.ikea_smart_plug_1
      - switch.ikea_smart_plug_3
    to: "on"

variables:
  timeouts:
    switch.tr_plug_4: 3600   # 1 hour
    switch.ikea_smart_plug_1: 14400  # 4 hours
    switch.ikea_smart_plug_3: 14400  # 4 hours
  triggered_switch: "{{ trigger.entity_id }}"
  delay_seconds: "{{ timeouts[triggered_switch] }}"

action:
  - delay:
      seconds: "{{ delay_seconds }}"
  - service: switch.turn_off
    target:
      entity_id: "{{ triggered_switch }}"
