alias: Downstairs Hallway Motion Lights
description: ""
triggers:
  - entity_id: sensor.tr_plug_1_power_factor
    above: 35
    trigger: numeric_state
  - entity_id: sensor.tr_plug_2_power_factor
    above: 35
    trigger: numeric_state
  - entity_id: sensor.tr_plug_3_power_factor
    above: 35
    trigger: numeric_state
  - entity_id: sensor.tr_plug_1_power_factor
    below: 35
    for: "00:00:01"
    trigger: numeric_state
  - entity_id: sensor.tr_plug_2_power_factor
    below: 35
    for: "00:00:01"
    trigger: numeric_state
  - entity_id: sensor.tr_plug_3_power_factor
    below: 35
    for: "00:00:01"
    trigger: numeric_state
conditions:
  - condition: state
    entity_id: input_boolean.motion_lights_master_switch
    state: "on"
actions:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: sensor.tr_plug_1_power_factor
                above: 35
              - condition: numeric_state
                entity_id: sensor.tr_plug_2_power_factor
                above: 35
              - condition: numeric_state
                entity_id: sensor.tr_plug_3_power_factor
                above: 35
        sequence:
          - target:
              entity_id: light.downstairs_hallway_lights
            data: |
              {% if is_state('input_boolean.night_light_mode', 'on') %} {
                "rgb_color": {{ states('input_text.night_light_color_tr').split(',') | map('int') | list }},
                "brightness_pct": 25
              } {% else %} {
                "brightness_pct": 25,
                "color_temp_kelvin": 2700
              } {% endif %}
            action: light.turn_on
      - conditions:
          - condition: and
            conditions:
              - condition: numeric_state
                entity_id: sensor.tr_plug_1_power_factor
                below: 35
              - condition: numeric_state
                entity_id: sensor.tr_plug_2_power_factor
                below: 35
              - condition: numeric_state
                entity_id: sensor.tr_plug_3_power_factor
                below: 35
        sequence:
          - target:
              entity_id: light.downstairs_hallway_lights
            action: light.turn_off
            data: {}
mode: restart
