alias: Downstairs Hallway Motion Lights
triggers:
  - entity_id: binary_sensor.mmwave_1_presence
    to: "on"
    trigger: state
  - entity_id: binary_sensor.mmwave_1_presence
    to: "off"
    for: "00:00:30"
    trigger: state
conditions:
  - condition: state
    entity_id: input_boolean.motion_lights_master_switch
    state: "on"
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.mmwave_1_presence
            state: "on"
        sequence:
          - target:
              entity_id: light.downstairs_hallway_lights
            data: |
              {% if is_state('input_boolean.night_light_mode', 'on') %} {
                "rgb_color": {{ states('input_text.night_light_color_tr').split(',') | map('int') | list }},
                "brightness_pct": 25
              } {% else %} {
                "brightness_pct": 25,
                "color_temp_kelvin": 2700
              } {% endif %}
            action: light.turn_on
      - conditions:
          - condition: state
            entity_id: binary_sensor.mmwave_1_presence
            state: "off"
        sequence:
          - target:
              entity_id: light.downstairs_hallway_lights
            action: light.turn_off
            data: {}
mode: restart
