alias: Front Lights - Sunset to Sunrise
trigger:
  - platform: state
    entity_id: sun.sun
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: above_horizon
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.front_lights
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: below_horizon
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.front_lights
            data:
              color_temp_kelvin: 2700
              brightness_pct: 5
mode: single
